### ISSUE TITLE
happypack好像并没有加速，反而拉慢的时间。

### ISSUE THREAD

**Issue by liuzhiyang0113** [NewPrototype/webpack4-es6-react#2]
我最近也在搞优化，现在的项目用了creat-react-app2(webpack4)的eject构建的。
使用happypack后反而打包时间增加了10秒，之前是33秒左右，用了happypack之后40+秒。

于是我一直在研究这个问题，然后看到了你的项目，我给你的项目配置去掉happypack，也是反而减少了几百毫秒。
我改的配置是这样的：
```
{
          test: /\.(js|jsx)$/,
          exclude: /(node_modules|bower_components)/, //排除
          include: [path.resolve(__dirname, 'src')], //包括
          loaders: ['cache-loader','babel-loader?cacheDirectory']
        }
```

所以我还在探究happypack加速的机制，是什么让打包时间增加了。

**Comment by NewPrototype** [comment]
happypack 比较看电脑内核的，如果电脑内核低的话，其实开启多线程，会让电脑cpu满了，整体速度会慢，```HappyPack.ThreadPool({ size: 4 })```,4可以根据电脑适当减少；
去除缓存，然后修改数字可以测试不同数字对应的速度
